os: "-osx"
language: node_js
node_js:
- node
notifications:
  email: false
install:
- npm install
deploy:
  provider: codedeploy
  wait_until_deployed: true
  app: kiddo-frontend
  skip_cleanup: true
  on: main
  access_key_id: "AKIAXO5P4GVWR5GJALVR"
  secret_access_key: "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"