os: "-osx"
language: node_js
node_js:
- node
notifications:
  email: false
install:
- npm install
deploy:
  provider: heroku
  app: kiddo-frontend
  skip_cleanup: true
  on: main
  api_key:
    secure: Bd4OLtpgRuA4lVpJMKX5BR/nKeFZuaHOIRiJYAoCGTc7qi5tMDjizJ5k0KrSZBThubZ0MfZWCpDZPx85JZLHWnMi/MHFjZ1kCXnmfFKuvrmJoXT/Muck7UkT+PE8+ZACtYu9CDikLcHNh7LA2NDzkCPbVrdK35y0C6FnRcB4oy4MBhKJhk5L/hoadkI0VOH7+1GETKSd7HC4FIWGZVUhDuvVxKsY7Sx7Uq7q38xsQdNvup3e3YUBZ0YC/7zPZ/Eb8jntIbCE8zQgP3CA5KxeQvgn4sbGqFEPGmp2k5yOxBEuz7bHSkElO/RbXZVD44hQ/UU7RwnjQEN9Uxdvu/tk2Er0YaFOKsHWiRw39gE/o+XZPiM2bh70qjEi5JIY3yc42vRG3Im07eUzGznSrTYlOKsqw1zZkQO85F9uGU1OP+5fRTNxaiEVu2clYGKHPimNLCEuxN+7aKQGBopDByIA0bIDDO1ERtc/YMpCChY3D27x6rr/g5zJnVKPjo7EdmC0lC/IpodvTKtyG2AYDjmV4Raona8VsznzILkJuYL1fNa3SnS64m4sJ5EdJW0+3rMlfaXt1oiCngHqmdolmU9i/NVkOFAnKaSKpyRqT7jjfBMF+v1QTXMO5kePXgJwiTYsmkUx9DN3CgfmeoGPEPlrwQYzaBCMYgEYsvtIsnIWV+A=
